services:
  app:
    container_name: akiba_for_artifacts
    image: akiba_for_artifacts:${VERSION:-3.1.2}
    ports:
      - "0.0.0.0:41778:22"
      - "0.0.0.0:41777:31777"
    build: .
    entrypoint: ["/bin/bash", "/home/akiba/binaries/entrypoint.sh"]
    command: ["/bin/bash", "./bin/akiba_db_daemon", "-c", "./resources/config.json"]
    working_dir: /home/akiba/akiba_db_daemon
    volumes:
      - /data/hongyuan/hongyuan-24:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:31777/test || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  akiba_data:
